export default {
  au: 'audio/basic',
  snd: 'audio/basic',
  pcm: 'audio/L24',
  mid: 'audio/mid',
  rmi: 'audio/mid',
  mp3: 'audio/mpeg',
  mp4: 'audio audio/mp4',
  aif: 'audio/x-aiff',
  aifc: 'audio/x-aiff',
  aiff: 'audio/x-aiff',
  m3u: 'audio/x-mpegurl',
  ra: 'audio/vnd.rn-realaudio',
  ram: 'audio/vnd.rn-realaudio',
  ogg: 'audio/ogg',
  vorbis: 'audio/vorbis',
  wav: 'audio/vnd.wav',
};
