export default {
  '3gp': 'video/3gpp',
  aac: 'video/aac',
  asf: 'video/x-ms-asf',
  asr: 'video/x-ms-asf',
  asx: 'video/x-ms-asf',
  avi: 'video/x-msvideo',
  lsf: 'video/x-la-asf',
  lsx: 'video/x-la-asf',
  mp2: 'video/mpeg',
  mpa: 'video/mpeg',
  mpe: 'video/mpeg',
  mpeg: 'video/mpeg',
  mpg: 'video/mpeg',
  mpv2: 'video/mpeg',
  mp3: 'vidoe/mp3',
  mp4: 'video/mp4',
  m4a: 'video/m4a',
  m4v: 'video/m4v',
  mkv: 'video/mkv',
  mov: 'video/quicktime',
  qt: 'video/quicktime',
  movie: 'video/x-sgi-movie',
  oog: 'video/oog',
  ts: 'video/ts',
  webm: 'video/webm',
};
